version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=fitnet_user
      - DB_PASSWORD=fitnet_password
      - DB_NAME=fitnet_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: fitnet_password
      MYSQL_DATABASE: fitnet_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

secrets:
  db-password:
    file: ./db-password.txt

